# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Colette Snow's Blog
email: colette@colettesnow.com
description: > # this means to ignore newlines until "baseurl:"
  Personal weblog of Colette Snow covering Anime, Technology and Video Games.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://testblog.colettesnow.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: colette_snow
github_username:  colettesnow

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
collections:
  cats:
    output: true
    permalink: /tagged/:name/
  exclude:
  - Gemfile
  - Gemfile.lock

# SEO
author:
  twitter: colette_snow

# Social settings

social:
  name: Colette Snow
  links:
    - https://twitter.com/colette_snow
    - https://www.facebook.com/colette.a.snow
    - https://www.linkedin.com/in/colettesnow
    - https://plus.google.com/u/0/106627462472248198069
    - https://github.com/colettesnow
    - http://about.me/colettesnow
    - http://www.pinterest.com/colettesnow/
    - https://t.me/colettesnow